export const BUDGET_ACTION_REQUEST = 'BUDGET_ACTION_REQUEST';

export const UPDATE_BUDGET_SUCCESS = 'UPDATE_BUDGET_SUCCESS ';
export const UPDATE_BUDGET_ERROR = 'UPDATE_BUDGET_ERROR ';

export const CREATE_BUDGET_SUCCESS = 'CREATE_BUDGET_SUCCESS ';
export const CREATE_BUDGET_ERROR = 'CREATE_BUDGET_ERROR ';

export const GET_BUDGET_SUCCESS = 'GET_BUDGET_SUCCESS ';
export const GET_BUDGET_ERROR = 'GET_BUDGET_ERROR ';
