export const EXPENSE_ACTION_ERROR = 'EXPENSE_ACTION_ERROR';
export const EXPENSE_ACTION_REQUEST = 'EXPENSE_ACTION_REQUEST';

export const LOAD_EXPENSES_SUCCESS = 'LOAD_EXPENSES_SUCCESS ';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS ';
export const UPDATE_EXPENSE_SUCCESS = 'UPDATE_EXPENSE_SUCCESS ';
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS ';
