export const GOAL_ACTION_REQUEST = 'GOAL_ACTION_REQUEST';

export const UPDATE_GOAL_SUCCESS = 'UPDATE_GOAL_SUCCESS ';
export const UPDATE_GOAL_ERROR = 'UPDATE_GOAL_ERROR ';

export const CREATE_GOAL_SUCCESS = 'CREATE_GOAL_SUCCESS ';
export const CREATE_GOAL_ERROR = 'CREATE_GOAL_ERROR ';

export const GET_GOAL_SUCCESS = 'GET_GOAL_SUCCESS ';
export const GET_GOAL_ERROR = 'GET_GOAL_ERROR ';
