export const TIP_ACTION_REQUEST = 'TIP_ACTION_REQUEST';

export const GET_TIP_SUCCESS = 'GET_TIP_SUCCESS';
export const GET_TIP_ERROR = 'GET_TIP_ERROR';

export const LOAD_TIPS_SUCCESS = 'LOAD_TIPS_SUCCESS';
export const LOAD_TIPS_ERROR = 'LOAD_TIPS_ERROR';

export const DELETE_TIPS_SUCCESS = 'DELETE_TIPS_SUCCESS';
export const DELETE_TIPS_ERROR = 'DELETE_TIPS_ERROR';
