export const USER_ACTION_ERROR = 'USER_ACTION_ERROR ';
export const USER_ACTION_REQUEST = 'USER_ACTION_REQUEST ';

export const LOAD_USERDATA_SUCCESS = 'LOAD_USERDATA_SUCCESS';
export const CHANGE_MONTH_SUCCESS = 'CHANGE_MONTH_SUCCESS';
export const SET_CURRENCY_SUCCESS = 'SET_CURRENCY_SUCCESS ';
export const SET_LANGUAGE_SUCCESS = 'SET_LANGUAGE_SUCCESS ';
export const SET_USERNAME_SUCCESS = 'SET_USERNAME_SUCCESS ';
export const SET_BUDGET_SUCCESS = 'SET_BUDGET_SUCCESS ';
export const SET_GOAL_SUCCESS = 'SET_GOAL_SUCCESS';
